apiVersion: apps/v1
kind: Deployment
metadata:
  name: wahl-o-chat-deployment
  namespace: wahl-o-chat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wahl-o-chat
  template:
    metadata:
      labels:
        app: wahl-o-chat
    spec:
      automountServiceAccountToken: false
      containers:
      - name: wahl-o-chat
        image: ghcr.io/fhswf/wahl-o-chat:0.9.0
        env:
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: openai-secret
              key: OPENAI_API_KEY
        - name: LANGCHAIN_API_KEY
          valueFrom:
            secretKeyRef:
              name: openai-secret
              key: LANGCHAIN_API_KEY
        - name: LANGCHAIN_TRACING_V2
          value: "true"
        - name: LANGCHAIN_PROJECT
          value: wahl-o-chat
        ports:
        - containerPort: 7860
---
apiVersion: v1
kind: Service
metadata:
  name: wahl-o-chat-service
  namespace: wahl-o-chat
spec:
  selector:
    app: wahl-o-chat
  ports:
    - protocol: TCP
      port: 7860
      targetPort: 7860
  type: ClusterIP
